[gateway]
timeout = "30s"

[graph]
path = "/graphql"
introspection = true

[cors]
allow_credentials = false
allow_origins = ["http://localhost:8080", "http://127.0.0.1:8080"]
allow_methods = ["GET", "POST", "OPTIONS"]
allow_headers = ["Content-Type"]
expose_headers = ["Access-Control-Allow-Origin"]
allow_private_network = true

[entity_caching]
enabled = true
storage = "redis"
ttl = "60s"

[entity_caching.redis]
url = "redis://redis:6379"
key_prefix = "grafbase-cache"
